---
# This playbook provides basic elements of a server we would like to maintain
- name: update apt-cache
  become: true
  apt:
    update_cache: yes

- name: install packages for sysadmin
  apt:
    pkg: nginx
    state: present
